import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import TanstackProvider from "../providers/TanstackProvider";
import { Toaster } from "../components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="antialiased"
      >
        <ClerkProvider>
          <TanstackProvider>
            {children}
            <Toaster />
          </TanstackProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}